# fly.toml app configuration file generated for axum-custom on 2024-08-31T15:24:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'axum-custom'
primary_region = 'lhr'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "blog_assets"
  destination = "/assets"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
